name: 'Merge branch'
description: 'A GitHub Action that manage git merge for any gitflow'
author: Pavel Potapkin
inputs:
  from_branch:
    description: 'Alias head_to_merge input'
    required: true
  target_branch:
    description: 'The name of target branch to merge'
    required: true
  head_to_merge:
    description: 'The branch name or hash to merge.'
    required: false
  message:
    description: 'Commit message'
    required: false
  disable_fastforwards:
    description: 'Does not merge the branch if no files have been changed'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'git-merge'
  color: 'blue'