name: 'Merge branch'
description: 'A GitHub Action that manage git merge for any gitflow'
author: Pavel Potapkin
inputs:
  from_branch:
    description: 'Alias head_to_merge input'
    required: true
  target_branch:
    description: 'The name of target branch to merge'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'git-merge'
  color: 'blue'